-- MySQL Script generated by MySQL Workbench
-- 10/22/15 22:24:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema nexthor_farmacia
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nexthor_farmacia` ;

-- -----------------------------------------------------
-- Schema nexthor_farmacia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nexthor_farmacia` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `nexthor_farmacia` ;

-- -----------------------------------------------------
-- Table `pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pais` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pais` (
  `idpais` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `estado` ENUM('Activo','Inactivo') NOT NULL DEFAULT 'Activo' COMMENT '',
  PRIMARY KEY (`idpais`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `laboratorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laboratorio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `laboratorio` (
  `idlaboratorio` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `idpais` INT(11) NOT NULL DEFAULT '1' COMMENT '',
  `estado` ENUM('Activo','Inactivo') NOT NULL DEFAULT 'Activo' COMMENT '',
  PRIMARY KEY (`idlaboratorio`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marca` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `marca` (
  `idmarca` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `estado` ENUM('Activo','Inactivo') NOT NULL DEFAULT 'Activo' COMMENT '',
  `idlaboratorio` INT(11) NOT NULL DEFAULT '1' COMMENT '',
  PRIMARY KEY (`idmarca`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `medicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medicamento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `medicamento` (
  `idmedicamento` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `idpais` INT(11) NOT NULL COMMENT 'pais de fabricacion',
  `idmarca` INT(11) NOT NULL DEFAULT '1' COMMENT '',
  `estado` ENUM('Activo','Inactivo') NOT NULL DEFAULT 'Activo' COMMENT '',
  PRIMARY KEY (`idmedicamento`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `registro_sanitario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registro_sanitario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `registro_sanitario` (
  `idregistro_sanitario` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NOT NULL COMMENT '',
  `idpais` INT(11) NOT NULL DEFAULT '1' COMMENT '',
  `estado` ENUM('Activo','Inactivo') NOT NULL DEFAULT 'Activo' COMMENT '',
  `idmedicamento` INT(11) NOT NULL DEFAULT '1' COMMENT '',
  PRIMARY KEY (`idregistro_sanitario`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
